name: Build MD for Hugo

on: 
  push:
    branches: [main]

jobs:
  do:
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v3

      - uses: debdutdeb/ino@yaml2md
        with:
          ino_path: ./ino.yml

      